# Podfile
source 'https://github.com/CocoaPods/Specs.git'

use_frameworks!

target 'DemoRxSwift' do
    pod 'RxSwift', '~> 5'
    pod 'RxCocoa', '~> 5'
    pod 'Alamofire', '~> 5.2'
    pod 'Moya/RxSwift', '~> 14.0'
end

# RxTest and RxBlocking make the most sense in the context of unit/integration tests
target 'DemoRxSwiftTests' do
    pod 'RxBlocking', '~> 5'
    pod 'RxTest', '~> 5'
end


